// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vnhtiudaceojvzlcyvav.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuaHRpdWRhY2VvanZ6bGN5dmF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkwNTQ3ODAsImV4cCI6MjA0NDYzMDc4MH0.I3guUADbOrdNMDYo13yogwiRhtLDi_PV8el2Cf9EqYo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);